config/routes.rb
FitCompete::Application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  root to: 'static_pages#home'
  resources :updates
  resources :challenges do 
    member do
      get :competitions
    end
  end
  resources :users do 
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :competitions
  
  match '/help',   :to => 'static_pages#help'
  match '/about',   :to => 'static_pages#about'
  match '/about',   :to => 'static_pages#about'
  get "static_pages/steps"
  get "static_pages/help"
  get '/users/:id', :to => "users#show", :as => :user
  
  namespace :api do
    get "user", controller: "users", action: "show"
    get "body_measurements", controller: "body_measurements", action: "show"
  
  end

end

app/models/fitbit/user.rb
class Fitbit::User < Fitbit::Data
  attr_accessor :fitbit_id, :display_name, :city, :state, :gender, :date_of_birth

  def initialize(user)
    super(user)

    if @logged_in && @linked
      user_info = user.fitbit_data.user_info['user']

      # Uncomment to view the data that is returned by the Fitbit service
      # ActiveRecord::Base.logger.info user_info

      @fitbit_id = user_info['encodedId']
      @linked = user.linked?
      @display_name = user_info['displayName']
      @city = user_info['city']
      @state = user_info['state']
      @gender = user_info['gender']
      @date_of_birth = user_info['date_of_birth']
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :name, :followed_id
  validates_presence_of :email
  has_many :challenges, dependent: :destroy
  has_many :updates, dependent: :destroy, :through => :challenges
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  has_many :competitions, foreign_key: "competitor_id", dependent: :destroy


	def self.new_with_session(params, session)
	  if session["devise.user_attributes"]
	    new(session["devise.user_attributes"], without_protection: true) do |user|
	      user.attributes = params
	      user.valid?
	    end
	  else
	    super
	  end    
	end

	def password_required?
	  super && provider.blank?
	end

	def self.from_omniauth(auth)
	  where(auth.slice(:provider, :uid)).first_or_create do |user|
	    user.provider = auth.provider
	    user.uid = auth.uid
	    user.username = auth.info.nickname
	    user.authtoken = auth.credentials.token
	    user.secrettoken = auth.credentials.secret
	  end
	end

	def update_with_password(params, *options)
	  if encrypted_password.blank?
	    update_attributes(params, *options)
	  else
	    super
	  end
	end

  def fitbit_client
    raise "Account is not linked with a Fitbit account" unless linked?
    return @fitbit_client if @fitbit_client

    @fitbit_client = Fitgem::Client.new(
      :consumer_key => "d4c64a56227a46a7950cf851f516748e",
      :consumer_secret => "405f2b469313493da01215e1ae10e05e",
      :token => current_user.authtoken,
      :secret => current_user.secrettoken
    )
  end

  def grab_data
    @activity = @fitbit_client.activities_on_date(Date.today.to_s)
  end

  def setUser
    user = User.find(params[:id])
  end

  def to_param
    username
  end

  def following?(other_user)
    relationships.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by_followed_id(other_user.id).destroy
  end

  def competing?(current_user)
    competitions.find_by_competitor_id(current_user.id)
  end

  def uncompete!(current_user)
    competitions.find_by_competitor_id(current_user).destroy
  end


end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController

  def show
    @user = Fitbit::User.new(current_user)
  end

  def fitbit_data
      raise "Account is not linked with a Fitbit account" unless linked?
      @client ||= Fitgem::Client.new(
                :consumer_key => ENV["d4c64a56227a46a7950cf851f516748e"],
                :consumer_secret => ENV["405f2b469313493da01215e1ae10e05e"],
                :token => oauth_token,
                :secret => oauth_secret,
                :user_id => uid
              )
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  	@recent_foods = client.recent_foods.all
  end

  def show 
    @user = User.find_by_username(params[:id])
    @challenges = @user.challenges.paginate(page: params[:page])

    unless @user.authtoken.blank?
      @users = User.paginate(page: params[:page])
      @fitbit_client = Fitgem::Client.new(
        :consumer_key => "d4c64a56227a46a7950cf851f516748e",
        :consumer_secret => "405f2b469313493da01215e1ae10e05e",
        :token => @user.authtoken,
        :secret => @user.secrettoken
      )
      @activity = @fitbit_client.activities_on_date(Date.today.to_s)
      @steps = @activity["summary"]["steps"]
    end
  end

  def following
    @title = "Following"
    @user = User.find_by_username(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find_by_username(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

end

app/helpers/api/users_helper.rb
module Api::UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id)) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<%# unless current_user.username?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<%# end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by_followed_id(@user),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
</li>

app/views/users/show.html.erb
<% provide(:title, 'Profile') %>
<% provide(:class, 'profile') %>
  <h1><%= @user.name %> has <%= @user.challenges.count %> challenges going.</h1>
  <ul class="meta">
    <li><%# @user ||= current_user %><a href="<% following_user_path(@user) %>"><% @user.followed_users.count %> following</a></li>
    <li><a href="<% followers_user_path(@user) %>"><% @user.followers.count %> followers</a></li>
    <li><%= render 'follow_form' if signed_in? %></li>
  </ul>

  <ul class="challenges">
    <% @user.challenges.each do |challenge| %>
      <li class="card">
        <h2><%= link_to challenge.task, :id => challenge.id, :controller => :challenges, :action => :show %></h2>
        <!-- <p><%= challenge.description %></p> -->
      </li>
    <% end %>
  </ul>
      <section>
        
        <%# @user ||= current_user %>
          <!-- <div class="stats">
            <a href="<%# following_user_path(@user) %>">
              <strong id="following" class="stat">
                <%# @user.followed_users.count %>
              </strong>
              following
            </a>
            <a href="<%# followers_user_path(@user) %>">
              <strong id="followers" class="stat">
                <%# @user.followers.count %>
              </strong>
              followers
            </a>
          </div> -->
      </section>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.challenges.count %></span>
    </section>
    <section>

    </section>
  </aside>
  <div class="span8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>