config/routes.rb
FitCompete::Application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  root to: 'static_pages#home'
  resources :updates
  resources :challenges do 
    member do
      get :competitions
    end
  end
  resources :users do 
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :competitions
  
  match '/help',   :to => 'static_pages#help'
  match '/about',   :to => 'static_pages#about'
  match '/about',   :to => 'static_pages#about'
  get "static_pages/steps"
  get "static_pages/help"
  get '/users/:id', :to => "users#show", :as => :user
  
  namespace :api do
    get "user", controller: "users", action: "show"
    get "body_measurements", controller: "body_measurements", action: "show"
  
  end

end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
  attr_accessible :description, :task
  belongs_to :user
  # validates :user_id, presence: true
  default_scope order: 'challenges.created_at DESC'
  has_many :updates, dependent: :destroy
  has_many :competitions, dependent: :destroy
  has_many :competitors, through: :competitions, source: :competitor
  has_many :reverse_relationships, foreign_key: "competitor_id",
                                   class_name:  "Competitor",
                                   dependent:   :destroy
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  def index 
  end

  def show 
    @user = current_user
    # @challenges = @user.challenges.paginate(page: params[:page])
    @challenges = @user.challenges.all
    @challenge = Challenge.find(params[:id])
    #@updates = @challenge.updates.all
    # @updates = @challenge.updates.build
    # @update = @challenge.updates.build
    # @challenges = current_user.challenges.all
    # @challenge = current_user.challenges.build(params[:challenge])
  end

  def new
    @challenges = current_user.challenges.all
    @challenge = current_user.challenges.build
  end

  def create
    @challenge = current_user.challenges.build(params[:challenge])
    if @challenge.save
      flash[:success] = "Challenge created!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end

  def update
    
  end

  def following
    @title = "Following"
    @challenge = User.find(params[:id])
    @challenges = @challenge.challenged_users.paginate(page: params[:page])
    render 'join'
  end

  def followers
    @title = "Followers"
    @challenge = User.find(params[:id])
    @challenges = @challenge.challenged.paginate(page: params[:page])
    render 'join'
  end

end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/_challenge.html.erb
<li>
  <span class="content"><%= challenge.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(challenge.created_at) %> ago.
  </span>
</li>

app/views/challenges/_join.html.erb
<%= form_for(@challenge.competitions.build(competitor_id: current_user.id)) do |f| %>
  <div><%= f.hidden_field :challenge_id, :value => @challenge.id %></div>
  <div><%= f.hidden_field :competitor_id, :value => current_user.id %></div>
  <%= f.submit "Join this challenge", class: "button join" %>
<% end %>

app/views/challenges/_leave.html.erb
<%= form_for(@challenge.competitions.build(competitor_id: current_user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Leave this challenge", class: "button leave" %>
<% end %>
<%# button_to "Unfollow", competitions_path(competitions), :method => 'delete' %>

app/views/challenges/new.html.erb
<h1>What are you working towards?</h1>

<%= form_for(@challenge) do |f| %>
  <div class="field"><%= f.label :task %><br />
  <%= f.text_field :task %></div>
  
  <div class="field"><%= f.label :description %><br />
  <%= f.text_field :description %></div>

  <div class="field"><%= f.submit "Add Challenge", :class => "button" %></div>
<% end %>

app/views/challenges/show.html.erb
<% provide(:title, @challenge.task) %>
<% provide(:class, 'challenge interior') %>
<h1><%= @challenge.task %></a></h1>
<!-- <h3 class="challenge-description"><%= @challenge.description %></h3>
<p>Posted <%= time_ago_in_words(@challenge.created_at) %> ago.</p> -->
<ul class="meta">
  <li class="username">Started by <%= link_to @user.name, :id => @user.username, :controller => :users, :action => :show %></li>
  <span>&#8226;</span>
  <li class="biking">Biking</li>
  <span>&#8226;</span>
  <li><a class="stats" href="<%# following_user_path(@user) %>"><%= @challenge.competitions.count %> competitors</a></li>
  <li>
    <%# unless current_user.username?(@user) %>
      <div id="follow_form">
      <% if current_user.competing?(@user) %>
        <%= render 'leave' %>
      <% else %>
        <%= render 'join' %>
      <% end %>
      </div>
    <%# end %>
  </li>
</ul>
<ul class="updates">

</ul>